name: yanderify
channels:
  - 1adrianb
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - pip:
    - asn1crypto=1.3.0
    - blas=1.0
    - brotlipy=0.7.0
    - ca-certificates=2020.6.24
    - certifi=2020.6.20
    - cffi=1.11.5
    - chardet=3.0.4
    - cloudpickle=1.5.0
    - cryptography=2.3.1
    - cuda100=1.0
    - cycler=0.10.0
    - dask-core=2.20.0
    - decorator=4.4.2
    - face_alignment=1.0.1
    - freetype=2.10.2
    - hdf5=1.8.18
    - icc_rt=2019.0.0
    - icu=58.2
    - idna=2.10
    - imageio=2.3.0
    - intel-openmp=2020.1
    - jpeg=9b
    - kiwisolver=1.2.0
    - libopencv=3.4.1
    - libpng=1.6.37
    - libtiff=4.1.0
    - lz4-c=1.9.2
    - matplotlib=2.2.2
    - mkl=2019.4
    - mkl-service=2.3.0
    - mkl_fft=1.1.0
    - mkl_random=1.1.0
    - networkx=2.4
    - ninja=1.9.0
    - numpy=1.15.0
    - numpy-base=1.15.0
    - olefile=0.46
    - opencv=3.4.1
    - openssl=1.0.2t
    - pandas=0.23.4
    - pillow=6.2.1
    - pip=20.1.1
    - py-opencv=3.4.1
    - pycparser=2.20
    - pyopenssl=19.0.0
    - pyparsing=2.4.7
    - pyqt=5.6.0
    - pysocks=1.7.1
    - python=3.7.1
    - python-dateutil=2.8.1
    - pytorch=1.0.0
    - pytz=2020.1
    - pywavelets=1.1.1
    - pyyaml=5.3.1
    - qt=5.6.2
    - requests=2.23.0
    - scikit-image=0.14.0
    - scikit-learn=0.19.2
    - scipy=1.1.0
    - setuptools=49.2.0
    - sip=4.18.1
    - six=1.11.0
    - sqlite=3.20.1
    - tk=8.6.10
    - toolz=0.10.0
    - torchvision=0.2.1
    - tornado=6.0.4
    - tqdm=4.24.0
    - urllib3=1.25.9
    - vc=14.1
    - wheel=0.34.2
    - xz=5.2.5
    - yaml=0.1.7
    - zlib=1.2.11
    - zstd=1.4.4
    - ffmpeg=4.0.2
    - x264=1.152.20180717
